export interface BankItem {
  name: string;
  code: string;
}

export const INDONESIAN_BANKS: BankItem[] = [
  { name: "Bank Central Asia (BCA)", code: "014" },
  { name: "Bank Mandiri", code: "008" },
  { name: "Bank Rakyat Indonesia (BRI)", code: "002" },
  { name: "Bank Negara Indonesia (BNI)", code: "009" },
  { name: "Bank Syariah Indonesia (BSI)", code: "451" },
  { name: "Bank Tabungan Negara (BTN)", code: "200" },
  { name: "CIMB Niaga", code: "022" },
  { name: "Bank Permata", code: "087" },
  { name: "Bank Danamon", code: "011" },
  { name: "Bank Jago", code: "542" },
  { name: "Allo Bank", code: "567" },
  { name: "SeaBank Indonesia", code: "535" },
  { name: "Bank Neo Commerce (BNC)", code: "490" },
  { name: "Jenius (BTPN)", code: "213" },
  { name: "Bank Muamalat", code: "147" },
  { name: "Bank Mega", code: "426" },
  { name: "OCBC NISP", code: "028" },
  { name: "Maybank Indonesia", code: "016" },
  { name: "Bank Bukopin", code: "441" },
  { name: "Bank Sinarmas", code: "153" },
  { name: "Bank BJB", code: "110" },
  { name: "Bank DKI", code: "111" },
  { name: "Bank Jatim", code: "114" },
  { name: "Bank Jateng", code: "113" },
  { name: "Bank DIY", code: "112" },
  { name: "Bank Sumut", code: "117" },
  { name: "Bank Riau Kepri", code: "119" },
  { name: "Bank Sumsel Babel", code: "120" },
  { name: "Bank Lampung", code: "121" },
  { name: "Bank Kalsel", code: "122" },
  { name: "Bank Kalbar", code: "123" },
  { name: "Bank Kaltimtara", code: "124" },
  { name: "Bank Kalteng", code: "125" },
  { name: "Bank Sulselbar", code: "126" },
  { name: "Bank Sulutgo", code: "127" },
  { name: "Bank NTB Syariah", code: "128" },
  { name: "Bank NTT", code: "130" },
  { name: "Bank Maluku Malut", code: "131" },
  { name: "Bank Papua", code: "132" },
  { name: "Bank Bengkulu", code: "133" },
  { name: "Bank Jambi", code: "134" },
  { name: "Bank Sulteng", code: "135" },
  { name: "Bank Sultra", code: "137" },
  { name: "Bank Victoria Internasional", code: "566" },
  { name: "Bank Maspion", code: "157" },
  { name: "Bank Jasa Jakarta", code: "472" },
  { name: "Bank MNC Internasional", code: "485" },
  { name: "Bank Woori Saudara", code: "212" },
  { name: "Bank KEB Hana Indonesia", code: "484" },
];
